# Use the latest OSRM backend image
FROM overv/openstreetmap-tile-server

# Set the working directory
WORKDIR /

# Copy the OSM PBF file into the image
COPY ./bangladesh-latest.osm.pbf /data/region.osm.pbf