version: '3.5'
services:

  mongodb-7-express:
    image: mongo-express:latest
    container_name: mongodb-7-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD-admin}
      ME_CONFIG_MONGODB_SERVER: mongodb-7
    depends_on:
      - mongodb-7

  mongodb-7:
    image: mongo:7
    container_name: mongodb-7
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD-admin}
    volumes:
      - ./volumes/vol-mongodb-7/data/db:/data/db
      - ./volumes/vol-mongodb-7/data/configdb:/data/configdb

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '0.0.0.0:8085:80'
    volumes:
      - ./volumes/vol-pgadmin:/var/lib/pgadmin    
    networks:
      - common

  postgres-16:
    image: postgres:16
    container_name: postgres-16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USERNAME-admin}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD-admin}
      # POSTGRES_DB: ${DB_POSTGRES_DATABASE}
    ports:
      - '0.0.0.0:5433:5432'
    volumes:
      - ./volumes/vol-postgres-16:/var/lib/postgresql/data
    networks:
      - common

  postgres-timescale-16:
    image: timescale/timescaledb:latest-pg12
    container_name: postgres-timescale-16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USERNAME-admin}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD-admin}
      POSTGRES_DB: benchmark
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - ./volumes/vol-postgres-timescale-16:/var/lib/postgresql/data
    networks:
      - common
    
  quest:
    image: questdb/questdb:latest
    container_name: quest
    ports:
      - "9000:9000"  # HTTP API
      - "9009:9009"  # InfluxDB Line Protocol
      - "8812:8812"  # Postgres Wire Protocol
    environment:
      QDB_DEBUG: false
    volumes:
      - ./volumes/vol-quest:/var/lib/questdb
    networks:
      - common

networks:
  common:
    name: common
    driver: bridge
