version: '3.5'
services:
  mariadb-10:
    image: mariadb:10
    container_name: mariadb-10
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_MYSQL_USERNAME-admin}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD-admin}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD-root}
    ports:
      - '0.0.0.0:6010:3306'
    volumes:
      - ./volumes/vol-mariadb-10:/var/lib/mysql
    networks:
      - common

  pgadmin-postgres-16:
    image: dpage/pgadmin4
    container_name: pgadmin-postgres-16
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '0.0.0.0:8085:80'
    volumes:
      - ./volumes/vol-pgadmin-postgres-16:/var/lib/pgadmin    
    networks:
      - common

  phpmyadmin-mariadb-10:
    depends_on:
      - mariadb-10
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-mariadb-10
    restart: always
    ports:
      - '0.0.0.0:8180:80'
    environment:
      PMA_HOST: mariadb-10
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD-root}
    networks:
      - common

  postgres-16:
    image: postgres:16
    container_name: postgres-16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USERNAME-admin}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD-admin}
      # POSTGRES_DB: ${DB_POSTGRES_DATABASE}
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - ./volumes/vol-postgres-16:/var/lib/postgresql/data
    networks:
      - common

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    restart: unless-stopped
    environment: 
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER-rabbit}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS-rabbit}
      RABBITMQ_DEFAULT_VHOST: 'vhost'
    ports:
      - '0.0.0.0:5672:5672'
      - '0.0.0.0:15672:15672'
    volumes:
      - ./volumes/vol-rabbitmq/data:/var/lib/rabbitmq/
      - ./volumes/vol-rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - common

networks:
  common:
    name: common
    driver: bridge
