version: '3.5'
services:

  mongodb-7-express:
    image: mongo-express:latest
    container_name: mongodb-7-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_DB_USERNAME-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_DB_PASSWORD-admin}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_SERVER_FOR_EXPRESS-mongodb-7}
      ME_CONFIG_MONGODB_URL: ${MONGO_DB_URL_FOR_EXPRESS-mongodb-7}
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: '0.5'
    depends_on:
      - mongodb-7
    networks:
      - common

  mongodb-7:
    image: mongo:7
    container_name: mongodb-7
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD-admin}
    deploy:
      resources:
        limits:
          cpus: '1.0'  # Limit to 8 CPU threads
          memory: 1G  # Limit to 10 GB of memory
        # reservations:
        #   cpus: '8.0'  # Reserve 8 CPU threads
        #   memory: 10G  # Reserve 10 GB of memory
    volumes:
      - ${VOL_BASE}/vol-mongodb-7/data/db:/data/db
      - ${VOL_BASE}/vol-mongodb-7/data/configdb:/data/configdb
      # - ${VOL_BASE}/vol-mongodb-7/config/:/etc/mongo/
    # command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    networks:
      - common  

  nominatim:
    build:
      context: ${DOCKER_FILES_BASE}/nominatim
    container_name: nominatim
    environment:
      PBF_PATH: /nominatim/files/bangladesh-latest.osm.pbf
      NOMINATIM_PASSWORD: postgres
    volumes:
      - ${VOL_BASE}/vol-nominatim/files:/nominatim/files
      - ${VOL_BASE}/vol-nominatim/data:/nominatim/data
      - ${VOL_BASE}/vol-nominatim/postgres_data:/var/lib/postgresql/12/main
      - ${VOL_BASE}/vol-nominatim/apache_logs:/var/log/apache2
      - ${VOL_BASE}/vol-nominatim/nominatim_logs:/var/log/nominatim
      - ${VOL_BASE}/vol-nominatim/nominatim_settings:/nominatim/settings
      - ${VOL_BASE}/vol-nominatim/postgresql_conf:/etc/postgresql/12/main/postgresql.conf
      - ${VOL_BASE}/vol-nominatim/tmp:/tmp/nominatim-tmp
    ports:
      - "8083:8080"
  # deploy:
  #   resources:
  #     limits:
  #       memory: 3G
  #       cpus: '1.0'   
    networks:
      - common  

  osm-tile-server:
    build:
      context: ${DOCKER_FILES_BASE}/osm-tile
    image: overv/openstreetmap-tile-server
    container_name: osm-tile-server
    volumes:
      - ${VOL_BASE}/vol-osm/data:/data/database/
      - ${VOL_BASE}/vol-osm/tiles:/data/tiles/
    ports:
      - "8082:80"
      - "54320:5432"
  # deploy:
  #   resources:
  #     limits:
  #       memory: 500M
  #       cpus: '1.0'   
    environment:
      ALLOW_CORS: enabled
      PGPASSWORD: osmtileserver
    command: run
  # command: ['import', 'run']
    networks:
      - common

  osrm-walking:
    container_name: osrm-walking
    build:
      context: ${DOCKER_FILES_BASE}/osrm-walking
  # command: osrm-routed --algorithm mld /data/bangladesh-latest.osrm
  # volumes:
  # - ${VOL_BASE}/vol-osrm-walking/data:/data
    ports:
      - "5001:5000"
    networks:
      - common
  osrm-bicycle:
    container_name: osrm-bicycle
    build:
      context: ${DOCKER_FILES_BASE}/osrm-bicycle
  # command: osrm-routed --algorithm mld /data/bangladesh-latest.osrm
  # volumes:
  #   - ${VOL_BASE}/vol-osrm-bicycle/data:/data    
    ports:
      - "5002:5000"
    networks:
      - common
  osrm-car:
    container_name: osrm-car
    build:
      context: ${DOCKER_FILES_BASE}/osrm-car
  # command: osrm-routed --algorithm mld /data/bangladesh-latest.osrm
    # volumes:
    #   - ${VOL_BASE}/vol-osrm-car/data:/data
    ports:
      - "5003:5000"
    networks:
      - common    

  overpass_api:
    container_name: overpass_api
    image: wiktorn/overpass-api
    environment:
      - OVERPASS_META=yes
      - OVERPASS_MODE=init
      - OVERPASS_PLANET_URL=https://download.geofabrik.de/asia/bangladesh-latest.osm.bz2
      - OVERPASS_RATE_LIMIT=1000
    volumes:
      - ${VOL_BASE}/vol-overpass/:/db
    ports:
      - "12345:80"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '0.0.0.0:8085:80'
    deploy:
      resources:
        limits:
          memory: 250M
          cpus: '1.0'    
    volumes:
      - ${VOL_BASE}/vol-pgadmin:/var/lib/pgadmin    
    networks:
      - common

  postgres-16-custom:
    build:
      context: ${DOCKER_FILES_BASE}/postgres
      dockerfile: postgres-16-w-gis-extensions.Dockerfile
    container_name: postgres-16-custom
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USERNAME-admin}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD-admin}
      # POSTGRES_DB: ${DB_POSTGRES_DATABASE}
    ports:
      - '0.0.0.0:5433:5432'
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '1.0'    
    volumes:
      - ${VOL_BASE}/vol-postgres-16:/var/lib/postgresql/data
    networks:
      - common

  redis-7-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-7-insight
    restart: always
    ports:
      - 5540:5540
    depends_on:
      - redis-7
    deploy:
      resources:
        limits:
          memory: 150M
          cpus: '0.5'
    volumes:
      - ${VOL_BASE}/vol-redis-7-insight:/data
    networks:
      - common  
    
  redis-7:
    image: redis:7
    container_name: redis-7
    restart: always
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          memory: 20M
          cpus: '1.0'
    volumes:
      - ${VOL_BASE}/vol-redis-7:/data
    networks:
      - common
        
    

networks:
  common:
    name: common
    driver: bridge
