# Use the latest OSRM backend image
FROM mediagis/nominatim:4.4

# Set the working directory
WORKDIR /

# Copy the OSM PBF file into the image
COPY ./bangladesh-latest.osm.pbf /nominatim/files/bangladesh-latest.osm.pbf

